version: '2'
services:
  mesos-chronos:
    depends_on: 
      - zk
    image: prodest/veronica-docker-chronos
    environment:
      CHRONOS_HTTP_PORT: '8090'
      CHRONOS_MASTER: zk://zk:2181/mesos-master
      CHRONOS_ZK_HOSTS: zk://zk:2181
      CHRONOS_ZK_PATH: /chronos-jobs
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PORT0: '8090'
      VERSION: 3.0.0
    stdin_open: true
    external_links:
    - zk:zk
    tty: true
    ports:
    - 8090:8090/tcp
  mesos-master:
    depends_on: 
      - zk
    image: prodest/veronica-docker-master:latest
    environment:
      MESOS_CLUSTER: main-cluster
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_PORT: '5050'
      MESOS_QUORUM: '1'
      MESOS_VERSION: 'false'
      MESOS_WORK_DIR: /var/lib/zookeeper
      MESOS_ZK: zk://zk:2181/mesos-master
      MESOS_HOSTNAME: mesos.safetruck.com.br
    entrypoint:
    - /usr/sbin/mesos-master
    external_links:
    - zk:zk
    tty: true
    ports:
    - 5050:5050/tcp
  mesos-agent-v2:
    depends_on: 
      - zk
    image: prodest/veronica-docker-slave:latest
    devices:
    - /dev/autofs:/dev/autofs:rwm
    stdin_open: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /:/host
    ports:
    - 5051:5051/tcp
    - 7077:7077/tcp
    - 8081:8081/tcp
    - 4040:4040/tcp
    # command:
    # - --ip_discovery_command=curl http://rancher-metadata/2015-07-25/self/container/primary_ip
    privileged: true
    environment:
      MESOS_CGROUPS_HIERARCHY: /sys/fs/cgroup
      MESOS_CGROUP_HIERARCHY: /host/sys/fs/cgroup
      MESOS_CLUSTER: main-cluster
      MESOS_CONTAINERIZERS: mesos
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT: 3mins
      MESOS_LAUNCHER: posix
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_MASTER: zk://zk:2181/mesos-master
      MESOS_PORT: '5051'
      MESOS_QUORUM: '1'
      MESOS_SYSTEMD_ENABLE_SUPPORT: 'false'
      MESOS_SYSTEMD_RUNTIME_DIRECTORY: /lib/systemd/system
      MESOS_VERSION: 'false'
      MESOS_WORK_DIR: /var/lib/zookeeper
      ZOOKEEPER_DATADIR: /var/lib/zookeeper
      MESOS_HOSTNAME: localhost
    entrypoint:
    - /usr/sbin/mesos-slave
    links:
    - zk:zk
    tty: true
  zk:
    image: rawmind/alpine-zk:3.4.9
    environment:
      JVMFLAGS: -Xmx128m -Xms128m
      ZK_DATA_DIR: /opt/zk/data
      ZK_INIT_LIMIT: '10'
      ZK_MAX_CLIENT_CXNS: '500'
      ZK_SYNC_LIMIT: '5'
      ZK_TICK_TIME: '2000'
    tty: true